### ISSUE TITLE
Where is the code of EBCC ?

### ISSUE THREAD

**Issue by WhisperT** [yuan-li/truth-inference-at-scale#1]
Hello yuan-li:
     I  observe that the code of ibcc and bwa are in this repositeriory. However, in your paper EBCC is proposed, which I can't find here. Will the code of EBCC be avaliable?

**Comment by yuan-li** [comment]
Hi @WhisperT 

I've just uploaded the mean-field vb implementation for ebcc. I'm working on an improved version of it, and was hoping that I can release them together. I will let you know when it's ready :)

**Comment by WhisperT** [comment]
Thank you for your patient reply.

**Comment by chenju1900** [comment]
Hi yuan-li:
Thank you for you share, I find that some baseline methods in your paper are not provided here. Is it convenient for you to share the entire experiments?
